///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ComonPortalAddModel {
/*
{
  "success": false,
  "message": "Error."
}
*/

  bool? success;
  String? message;

  ComonPortalAddModel({
    this.success,
    this.message,
  });
  ComonPortalAddModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    return data;
  }
}
