///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CustomerListModelData {
/*
{
  "id": 4,
  "name": "Ali Arif",
  "email": "aliasgar.arif@gmail.coms",
  "email_verified_at": null,
  "created_at": "2022-04-11T08:49:38.000000Z",
  "updated_at": "2022-04-11T08:49:38.000000Z",
  "phone": "322558",
  "country": "India"
}
*/

  int? id;
  String? name;
  String? email;
  String? emailVerifiedAt;
  String? createdAt;
  String? updatedAt;
  String? phone;
  String? country;

  CustomerListModelData({
    this.id,
    this.name,
    this.email,
    this.emailVerifiedAt,
    this.createdAt,
    this.updatedAt,
    this.phone,
    this.country,
  });
  CustomerListModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    emailVerifiedAt = json['email_verified_at']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    phone = json['phone']?.toString();
    country = json['country']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['email_verified_at'] = emailVerifiedAt;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['phone'] = phone;
    data['country'] = country;
    return data;
  }
}

class CustomerListModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 4,
      "name": "Ali Arif",
      "email": "aliasgar.arif@gmail.coms",
      "email_verified_at": null,
      "created_at": "2022-04-11T08:49:38.000000Z",
      "updated_at": "2022-04-11T08:49:38.000000Z",
      "phone": "322558",
      "country": "India"
    }
  ],
  "message": ""
}
*/

  bool? success;
  List<CustomerListModelData?>? data;
  String? message;

  CustomerListModel({
    this.success,
    this.data,
    this.message,
  });
  CustomerListModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <CustomerListModelData>[];
      v.forEach((v) {
        arr0.add(CustomerListModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
