///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ListAllBackupModelData {
/*
{
  "backup_id": 1,
  "portal_id": 1,
  "status": 2,
  "message": "Backup failed: Connection issue!",
  "backup_time": "2022-04-15 10:50:10",
  "portal_name": "Moco",
  "portal_url": "http://13.238.226.225/use-case-to-improve-user-experience-using-screen-flows-in-salesforce/",
  "customer_name": "Ali Arif"
}
*/

  int? backupId;
  int? portalId;
  int? status;
  String? message;
  String? backupTime;
  String? portalName;
  String? portalUrl;
  String? customerName;

  ListAllBackupModelData({
    this.backupId,
    this.portalId,
    this.status,
    this.message,
    this.backupTime,
    this.portalName,
    this.portalUrl,
    this.customerName,
  });
  ListAllBackupModelData.fromJson(Map<dynamic, dynamic> json) {
    backupId = json['backup_id']?.toInt();
    portalId = json['portal_id']?.toInt();
    status = json['status']?.toInt();
    message = json['message']?.toString();
    backupTime = json['backup_time']?.toString();
    portalName = json['portal_name']?.toString();
    portalUrl = json['portal_url']?.toString();
    customerName = json['customer_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['backup_id'] = backupId;
    data['portal_id'] = portalId;
    data['status'] = status;
    data['message'] = message;
    data['backup_time'] = backupTime;
    data['portal_name'] = portalName;
    data['portal_url'] = portalUrl;
    data['customer_name'] = customerName;
    return data;
  }
}

class ListAllBackupModel {
/*
{
  "success": true,
  "data": [
    {
      "backup_id": 1,
      "portal_id": 1,
      "status": 2,
      "message": "Backup failed: Connection issue!",
      "backup_time": "2022-04-15 10:50:10",
      "portal_name": "Moco",
      "portal_url": "http://13.238.226.225/use-case-to-improve-user-experience-using-screen-flows-in-salesforce/",
      "customer_name": "Ali Arif"
    }
  ],
  "message": ""
}
*/

  bool? success;
  List<ListAllBackupModelData?>? data;
  String? message;

  ListAllBackupModel({
    this.success,
    this.data,
    this.message,
  });
  ListAllBackupModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ListAllBackupModelData>[];
      v.forEach((v) {
        arr0.add(ListAllBackupModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
