///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PortalTypeModelDataPortalTypes {
/*
{
  "type": "laravel",
  "value": "Laravel"
}
*/

  String? type;
  String? value;

  PortalTypeModelDataPortalTypes({
    this.type,
    this.value,
  });
  PortalTypeModelDataPortalTypes.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['value'] = value;
    return data;
  }
}

class PortalTypeModelData {
/*
{
  "portal_types": [
    {
      "type": "laravel",
      "value": "Laravel"
    }
  ]
}
*/

  List<PortalTypeModelDataPortalTypes?>? portalTypes;

  PortalTypeModelData({
    this.portalTypes,
  });
  PortalTypeModelData.fromJson(Map<String, dynamic> json) {
    if (json['portal_types'] != null) {
      final v = json['portal_types'];
      final arr0 = <PortalTypeModelDataPortalTypes>[];
      v.forEach((v) {
        arr0.add(PortalTypeModelDataPortalTypes.fromJson(v));
      });
      portalTypes = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (portalTypes != null) {
      final v = portalTypes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['portal_types'] = arr0;
    }
    return data;
  }
}

class PortalTypeModel {
/*
{
  "success": true,
  "data": {
    "portal_types": [
      {
        "type": "laravel",
        "value": "Laravel"
      }
    ]
  },
  "message": ""
}
*/

  bool? success;
  PortalTypeModelData? data;
  String? message;

  PortalTypeModel({
    this.success,
    this.data,
    this.message,
  });
  PortalTypeModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? PortalTypeModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
