///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PortalAddFailModel {
/*
{
  "success": false,
  "message": "Error.",
  "data": "Cannot connect to user.com:70. Error 101. Network is unreachable"
}
*/

  bool? success;
  String? message;
  String? data;

  PortalAddFailModel({
    this.success,
    this.message,
    this.data,
  });
  PortalAddFailModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = json['data']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['data'] = this.data;
    return data;
  }
}
