///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PortalAddModelData {
/*
{
  "name": "Test4",
  "url": "www.test4.com/admin",
  "host": "www.test4.com",
  "username": "Test 4",
  "password": "123456",
  "port": "port 35",
  "root_folder": "/Sd/Track",
  "plan_start_date": "2022-04-15",
  "plan_end_date": "2023-04-20",
  "user_id": "8",
  "updated_at": "2022-04-14T09:43:35.000000Z",
  "created_at": "2022-04-14T09:43:35.000000Z",
  "id": 4
}
*/

  String? name;
  String? url;
  String? host;
  String? username;
  String? password;
  String? port;
  String? rootFolder;
  String? planStartDate;
  String? planEndDate;
  String? userId;
  String? updatedAt;
  String? createdAt;
  int? id;

  PortalAddModelData({
    this.name,
    this.url,
    this.host,
    this.username,
    this.password,
    this.port,
    this.rootFolder,
    this.planStartDate,
    this.planEndDate,
    this.userId,
    this.updatedAt,
    this.createdAt,
    this.id,
  });
  PortalAddModelData.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
    host = json['host']?.toString();
    username = json['username']?.toString();
    password = json['password']?.toString();
    port = json['port']?.toString();
    rootFolder = json['root_folder']?.toString();
    planStartDate = json['plan_start_date']?.toString();
    planEndDate = json['plan_end_date']?.toString();
    userId = json['user_id']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    data['host'] = host;
    data['username'] = username;
    data['password'] = password;
    data['port'] = port;
    data['root_folder'] = rootFolder;
    data['plan_start_date'] = planStartDate;
    data['plan_end_date'] = planEndDate;
    data['user_id'] = userId;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    return data;
  }
}

class PortalAddModel {
/*
{
  "success": true,
  "data": {
    "name": "Test4",
    "url": "www.test4.com/admin",
    "host": "www.test4.com",
    "username": "Test 4",
    "password": "123456",
    "port": "port 35",
    "root_folder": "/Sd/Track",
    "plan_start_date": "2022-04-15",
    "plan_end_date": "2023-04-20",
    "user_id": "8",
    "updated_at": "2022-04-14T09:43:35.000000Z",
    "created_at": "2022-04-14T09:43:35.000000Z",
    "id": 4
  },
  "message": "Portal added successfully."
}
*/

  bool? success;
  PortalAddModelData? data;
  String? message;

  PortalAddModel({
    this.success,
    this.data,
    this.message,
  });
  PortalAddModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? PortalAddModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
