///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RestoreListModelData {
/*
{
  "restore_id": 1,
  "portal_id": 10,
  "status": 1,
  "message": "Restore Completed",
  "restore_time": "2022-04-18 19:31:53",
  "portal_name": "Rain2",
  "portal_url": "moco.rcstaging.co.in",
  "customer_name": "Ali Arif"
}
*/

  int? restoreId;
  int? portalId;
  int? status;
  String? message;
  String? restoreTime;
  String? portalName;
  String? portalUrl;
  String? customerName;

  RestoreListModelData({
    this.restoreId,
    this.portalId,
    this.status,
    this.message,
    this.restoreTime,
    this.portalName,
    this.portalUrl,
    this.customerName,
  });
  RestoreListModelData.fromJson(Map<String, dynamic> json) {
    restoreId = json['restore_id']?.toInt();
    portalId = json['portal_id']?.toInt();
    status = json['status']?.toInt();
    message = json['message']?.toString();
    restoreTime = json['restore_time']?.toString();
    portalName = json['portal_name']?.toString();
    portalUrl = json['portal_url']?.toString();
    customerName = json['customer_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['restore_id'] = restoreId;
    data['portal_id'] = portalId;
    data['status'] = status;
    data['message'] = message;
    data['restore_time'] = restoreTime;
    data['portal_name'] = portalName;
    data['portal_url'] = portalUrl;
    data['customer_name'] = customerName;
    return data;
  }
}

class RestoreListModel {
/*
{
  "success": true,
  "data": [
    {
      "restore_id": 1,
      "portal_id": 10,
      "status": 1,
      "message": "Restore Completed",
      "restore_time": "2022-04-18 19:31:53",
      "portal_name": "Rain2",
      "portal_url": "moco.rcstaging.co.in",
      "customer_name": "Ali Arif"
    }
  ],
  "message": ""
}
*/

  bool? success;
  List<RestoreListModelData?>? data;
  String? message;

  RestoreListModel({
    this.success,
    this.data,
    this.message,
  });
  RestoreListModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <RestoreListModelData>[];
      v.forEach((v) {
        arr0.add(RestoreListModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
