///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RestoreAddModelData {
/*
{
  "portal_id": "10",
  "backup_id": "40",
  "status": 0,
  "message": "Pending",
  "updated_at": "2022-04-20T06:28:17.000000Z",
  "created_at": "2022-04-20T06:28:17.000000Z",
  "id": 7
}
*/

  String? portalId;
  String? backupId;
  int? status;
  String? message;
  String? updatedAt;
  String? createdAt;
  int? id;

  RestoreAddModelData({
    this.portalId,
    this.backupId,
    this.status,
    this.message,
    this.updatedAt,
    this.createdAt,
    this.id,
  });
  RestoreAddModelData.fromJson(Map<String, dynamic> json) {
    portalId = json['portal_id']?.toString();
    backupId = json['backup_id']?.toString();
    status = json['status']?.toInt();
    message = json['message']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['portal_id'] = portalId;
    data['backup_id'] = backupId;
    data['status'] = status;
    data['message'] = message;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    return data;
  }
}

class RestoreAddModel {
/*
{
  "success": true,
  "data": {
    "portal_id": "10",
    "backup_id": "40",
    "status": 0,
    "message": "Pending",
    "updated_at": "2022-04-20T06:28:17.000000Z",
    "created_at": "2022-04-20T06:28:17.000000Z",
    "id": 7
  },
  "message": "Restore added successfully."
}
*/

  bool? success;
  RestoreAddModelData? data;
  String? message;

  RestoreAddModel({
    this.success,
    this.data,
    this.message,
  });
  RestoreAddModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? RestoreAddModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
