///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ShLoginErrorNewModelData {
/*
{
  "success": "false"
}
*/

  String? success;

  ShLoginErrorNewModelData({
    this.success,
  });
  ShLoginErrorNewModelData.fromJson(Map<String, dynamic> json) {
    success = json['success']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class ShLoginErrorNewModel {
/*
{
  "success": false,
  "message": "Invalid emaail or password.",
  "data": {
    "success": "false"
  }
}
*/

  bool? success;
  String? message;
  ShLoginErrorNewModelData? data;

  ShLoginErrorNewModel({
    this.success,
    this.message,
    this.data,
  });
  ShLoginErrorNewModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? ShLoginErrorNewModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
