///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SignUpModelData {
/*
{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYzYxOWM3N2NlYWEyYWZlZjc1ZDQwMzg0ZDcwNDZkODZkNzRiYWExYzNmMThkZTAxOTAxNzI1ZTQ1ODM5YzJmOWY1MDNmZjY3NjViZGFiNTQiLCJpYXQiOjE2NDk3NjQ1MDUuMzMwOTI3LCJuYmYiOjE2NDk3NjQ1MDUuMzMwOTMxLCJleHAiOjE2ODEzMDA1MDUuMzI4MzI4LCJzdWIiOiI3Iiwic2NvcGVzIjpbXX0.YjikaydQ4thVMg6PU2IX17_NoIgBIGKWCrG4oZZ-Dy2KANJ7HAMjo5gCGbRgPfGR83b-LNuxLavkq6H3G_ReCkulZ-kvnCJ7LgQbyTDKFRUftNo1oDPZ6CVTacnUC-GKuhpixOovfa5BgRoGGdgQWtPfNMl7LJe6ukM8dUCwA8L3A-dZYut7xVK_ewOumh93oxEYU-Zr6xM4-SjS7WucmAMI1d_dG8INWeKfryTrSrjYATYBdFUHqPV5PuY6OBbCYSseAgYByE9X2U0mozOyL93wtdKHMt2CrKbN4dCLDRXs7Zqpwdf5ubd-OqIhXuRQ2IAwNJQzBkwz3mQJZKgGmR6PFSB28XsAqRbenbMCB6QVRLNJfyDMa98bk8n6JmbtRnrW7CGQ6YvhZbqkwF13yNbI59KvzRl5vggO8d8aoDROE_DlrjbS_9fTmD7NuUE2WEc9Tm7xYmLpKdDwRhocq8v_92mJ_Hda_8f8AnGKegLnD2dBqsVqmBYxY3N2z6vXlJ5xr7-aTwFpmqx6IIE9zzvoYpNro-GP0QbCFaedAPv13_sHqpzm1XbCQ1-GBM4akTGGIIN7cKjiPUyetKxnbI1GCpnBzgfwWWCV9DhJpwLvWD3x9m461Vy_065chUU_tqGSvkwkw26ncAJCRdPmXAkbFfqu-jOon5iXlg0wWhs",
  "name": "Test3",
  "email": "test3@gmail.com",
  "phone": "7845124578",
  "country": "India",
  "is_admin": 0
}
*/

  String? token;
  String? name;
  String? email;
  String? phone;
  String? country;
  int? isAdmin;

  SignUpModelData({
    this.token,
    this.name,
    this.email,
    this.phone,
    this.country,
    this.isAdmin,
  });
  SignUpModelData.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    country = json['country']?.toString();
    isAdmin = json['is_admin']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    data['name'] = name;
    data['email'] = email;
    data['phone'] = phone;
    data['country'] = country;
    data['is_admin'] = isAdmin;
    return data;
  }
}

class SignUpModel {
/*
{
  "success": true,
  "data": {
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYzYxOWM3N2NlYWEyYWZlZjc1ZDQwMzg0ZDcwNDZkODZkNzRiYWExYzNmMThkZTAxOTAxNzI1ZTQ1ODM5YzJmOWY1MDNmZjY3NjViZGFiNTQiLCJpYXQiOjE2NDk3NjQ1MDUuMzMwOTI3LCJuYmYiOjE2NDk3NjQ1MDUuMzMwOTMxLCJleHAiOjE2ODEzMDA1MDUuMzI4MzI4LCJzdWIiOiI3Iiwic2NvcGVzIjpbXX0.YjikaydQ4thVMg6PU2IX17_NoIgBIGKWCrG4oZZ-Dy2KANJ7HAMjo5gCGbRgPfGR83b-LNuxLavkq6H3G_ReCkulZ-kvnCJ7LgQbyTDKFRUftNo1oDPZ6CVTacnUC-GKuhpixOovfa5BgRoGGdgQWtPfNMl7LJe6ukM8dUCwA8L3A-dZYut7xVK_ewOumh93oxEYU-Zr6xM4-SjS7WucmAMI1d_dG8INWeKfryTrSrjYATYBdFUHqPV5PuY6OBbCYSseAgYByE9X2U0mozOyL93wtdKHMt2CrKbN4dCLDRXs7Zqpwdf5ubd-OqIhXuRQ2IAwNJQzBkwz3mQJZKgGmR6PFSB28XsAqRbenbMCB6QVRLNJfyDMa98bk8n6JmbtRnrW7CGQ6YvhZbqkwF13yNbI59KvzRl5vggO8d8aoDROE_DlrjbS_9fTmD7NuUE2WEc9Tm7xYmLpKdDwRhocq8v_92mJ_Hda_8f8AnGKegLnD2dBqsVqmBYxY3N2z6vXlJ5xr7-aTwFpmqx6IIE9zzvoYpNro-GP0QbCFaedAPv13_sHqpzm1XbCQ1-GBM4akTGGIIN7cKjiPUyetKxnbI1GCpnBzgfwWWCV9DhJpwLvWD3x9m461Vy_065chUU_tqGSvkwkw26ncAJCRdPmXAkbFfqu-jOon5iXlg0wWhs",
    "name": "Test3",
    "email": "test3@gmail.com",
    "phone": "7845124578",
    "country": "India",
    "is_admin": 0
  },
  "message": "Customer registered successfully."
}
*/

  bool? success;
  SignUpModelData? data;
  String? message;

  SignUpModel({
    this.success,
    this.data,
    this.message,
  });
  SignUpModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? SignUpModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
