///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ViewPortalModelData {
/*
{
  "id": 1,
  "name": "Test Mage",
  "url": "https://testmage.digitalsummation.com/pub/",
  "username": "testmag",
  "password": "zaO3B1yGvwek",
  "port": "22",
  "root_folder": "public_html",
  "created_at": "2022-05-06T06:37:58.000000Z",
  "updated_at": "2022-05-10T10:20:14.000000Z",
  "user_id": 13,
  "plan_start_date": "2022-05-09",
  "plan_end_date": "2023-05-09",
  "host": "testmage.digitalsummation.com",
  "mysql_host": "localhost",
  "mysql_username": "testmag_magen22",
  "mysql_password": "pP7014!c@S",
  "mysql_database": "testmag_magen22",
  "mysql_port": "3306",
  "portal_type": "magento"
}
*/

  int? id;
  String? name;
  String? url;
  String? username;
  String? password;
  String? port;
  String? rootFolder;
  String? createdAt;
  String? updatedAt;
  int? userId;
  String? planStartDate;
  String? planEndDate;
  String? host;
  String? mysqlHost;
  String? mysqlUsername;
  String? mysqlPassword;
  String? mysqlDatabase;
  String? mysqlPort;
  String? portalType;

  ViewPortalModelData({
    this.id,
    this.name,
    this.url,
    this.username,
    this.password,
    this.port,
    this.rootFolder,
    this.createdAt,
    this.updatedAt,
    this.userId,
    this.planStartDate,
    this.planEndDate,
    this.host,
    this.mysqlHost,
    this.mysqlUsername,
    this.mysqlPassword,
    this.mysqlDatabase,
    this.mysqlPort,
    this.portalType,
  });
  ViewPortalModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    url = json['url']?.toString();
    username = json['username']?.toString();
    password = json['password']?.toString();
    port = json['port']?.toString();
    rootFolder = json['root_folder']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    userId = json['user_id']?.toInt();
    planStartDate = json['plan_start_date']?.toString();
    planEndDate = json['plan_end_date']?.toString();
    host = json['host']?.toString();
    mysqlHost = json['mysql_host']?.toString();
    mysqlUsername = json['mysql_username']?.toString();
    mysqlPassword = json['mysql_password']?.toString();
    mysqlDatabase = json['mysql_database']?.toString();
    mysqlPort = json['mysql_port']?.toString();
    portalType = json['portal_type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['url'] = url;
    data['username'] = username;
    data['password'] = password;
    data['port'] = port;
    data['root_folder'] = rootFolder;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['user_id'] = userId;
    data['plan_start_date'] = planStartDate;
    data['plan_end_date'] = planEndDate;
    data['host'] = host;
    data['mysql_host'] = mysqlHost;
    data['mysql_username'] = mysqlUsername;
    data['mysql_password'] = mysqlPassword;
    data['mysql_database'] = mysqlDatabase;
    data['mysql_port'] = mysqlPort;
    data['portal_type'] = portalType;
    return data;
  }
}

class ViewPortalModel {
/*
{
  "success": true,
  "data": {
    "id": 1,
    "name": "Test Mage",
    "url": "https://testmage.digitalsummation.com/pub/",
    "username": "testmag",
    "password": "zaO3B1yGvwek",
    "port": "22",
    "root_folder": "public_html",
    "created_at": "2022-05-06T06:37:58.000000Z",
    "updated_at": "2022-05-10T10:20:14.000000Z",
    "user_id": 13,
    "plan_start_date": "2022-05-09",
    "plan_end_date": "2023-05-09",
    "host": "testmage.digitalsummation.com",
    "mysql_host": "localhost",
    "mysql_username": "testmag_magen22",
    "mysql_password": "pP7014!c@S",
    "mysql_database": "testmag_magen22",
    "mysql_port": "3306",
    "portal_type": "magento"
  },
  "message": ""
}
*/

  bool? success;
  ViewPortalModelData? data;
  String? message;

  ViewPortalModel({
    this.success,
    this.data,
    this.message,
  });
  ViewPortalModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? ViewPortalModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
